insert into tvshows values(0, 0, '30rock', 'static/img/tv/30rock.jpg', '', 'Liz Lemon finds herself in a dilemma.  Cabletown is in trouble, Jack is gone, and Liz must take over.');
insert into tvshows values(1, 1, 'Gossip Girl', 'static/img/tv/gossipgirl.jpg', '', 'Chuck and Blair blah blah');
insert into tvshows values(2, 1, 'Revenge', 'static/img/tv/revenge.jpg', '', 'She gets her revenge');

insert into genres values(0, 'Comedy');
insert into genres values(1, 'Girly');
insert into genres values(2, 'Cops');
insert into genres values(3, 'Dance');
insert into genres values(4, 'Sing');
insert into genres values(5, 'Reality');
insert into genres values(6, 'Mystery');
insert into genres values(7, 'Game Show');
insert into genres values(8, 'Cooking');
insert into genres values(9, 'Drama');
insert into genres values(10, 'Shopping');
insert into genres values(11, 'Sci Fi');
insert into genres values(12, 'Bro');
insert into genres values(13, 'Sports');
insert into genres values(14, 'Talk Show');
insert into genres values(15, 'Late Nite');
insert into genres values(16, 'Cartoons');
insert into genres values(17, 'News');
insert into genres values(18, 'Music');
insert into genres values(19, 'Cars');
insert into genres values(20, 'Horror');
insert into genres values(21, 'Vampires');
insert into genres values(22, 'Suspense');
insert into genres values(23, 'Super Hero');

insert into friends values(1, '/static/img/friends/friend1.jpg','Sam Gruskin');
insert into friends values(2, '/static/img/friends/friend2.jpg','Erin Smith');
insert into friends values(3, '/static/img/friends/friend3.jpg','Alex Cheng');
insert into friends values(4, '/static/img/friends/friend4.jpg','Markus Bohn');
insert into friends values(5, '/static/img/friends/friend5.jpg','Aatman Shah');
insert into friends values(6, '/static/img/friends/friend6.jpg','Andrew Milne');