insert into users values(0, 'Jenny', 'static/img/users/jenny.jpg');
insert into users values(1, 'Neha', 'static/img/users/neha.jpg');

insert into tvshows values(0, 0, '30rock', 'static/img/tv/30rock.jpg',   'http://www.youtube.com/watch?v=K_P7yWnAAd0', 'Season 5, Episode 4', 'Liz Lemon finds herself in a dilemma.  Cabletown is in trouble, Jack is gone, and Liz must take over.');
insert into tvshows values(1, 1, 'Gossip Girl', 'static/img/tv/gossipgirl.jpg', 'http://www.youtube.com/watch?v=P0oWK67kuNQ', 'Season 5, Episode 4','Chuck and Blair have an adulterous affair');
insert into tvshows values(2, 1, 'Revenge', 'static/img/tv/revenge.jpg', 'http://www.youtube.com/watch?v=kHIaORMG-AM','Season 1, Episode 8','Emily moves closer to exposing the Graysons.');
insert into tvshows values(3, 0, 'How I Met Your Mother', 'static/img/tv/himym_S07E01.jpg', 'http://www.youtube.com/watch?v=TV-NhfgoA7A', 'Season 7, Episode 1','The Best Man Ted attends a wedding');
insert into tvshows values(4, 0, 'How I Met Your Mother', 'static/img/tv/himym_S07E02.jpg', 'http://www.youtube.com/watch?v=TV-NhfgoA7A', 'Season 7, Episode 2','The Naked Truth');		
insert into tvshows values(5, 0, 'How I Met Your Mother', 'static/img/tv/himym_S07E03.jpg', 'http://www.youtube.com/watch?v=TV-NhfgoA7A', 'Season 7, Episode 3','Ducky Tie');
insert into tvshows values(6, 0, 'New Girl', 'static/img/tv/newgirl_S01E01.jpg', 'http://www.youtube.com/watch?v=2qqojuj1zoU', 'Season 1, Episode 1','Pilot Jess moves in with the guys');
insert into tvshows values(7, 0, 'New Girl', 'static/img/tv/newgirl_S01E02.jpg', 'http://www.youtube.com/watch?v=2qqojuj1zoU', 'Season 1, Episode 2','Kryptonite');
insert into tvshows values(8, 0, 'New Girl', 'static/img/tv/newgirl_S01E03.jpg', 'http://www.youtube.com/watch?v=2qqojuj1zoU', 'Season 1, Episode 3','Wedding Jess tries to help Nick make his ex jealous, but everything just ends up going wrong');
insert into tvshows values(9, 0, '90210', 'static/img/tv/90210.jpg', 'http://www.youtube.com/watch?v=http://www.youtube.com/watch?v=LetvuCG35ug', 'Season 3, Episode 3','Naomi has a water jet accident, and Liam comes to her rescue.');
insert into tvshows values (10, 11, 'Fringe', 'static/img/tv/fringe.jpg', 'http://www.youtube.com/watch?v=29bSzbqZ3xE', 'Season 1, Episode 2', "The Fringe team is pushed to the brink as they try to save every living person from the schemes of Jones superior.");
insert into tvshows values (11, 11, 'Battlestar Galactica', 'static/img/tv/bsg.jpg', 'http://www.youtube.com/watch?v=q2x14ZhEc9k', 'Season 3, Episode 5', "Despite Anders' success at neutralizing the Cylon gun batteries, Adama's volunteer attack force sustains heavy casualties. Cylon Raiders pursue the Vipers and Centurions board the Galactica. Kara attempts to decipher the meaning of Hera's drawing and rescue the Galactica.");
insert into tvshows values (12, 11, 'Doctor Who', 'static/img/tv/doctorwho.jpg', 'http://www.youtube.com/watch?v=EpbmMhNe6aA', 'Season 6, Episode 12', "As the Doctor prepares for his inevitable death at Lake Silencio, he visits a former roommate and learns that the Cybermen are responsible for a series of disappearances at a local department store and resolves to investigate.");


insert into genres values(0, 'Comedy');
insert into genres values(1, 'Girly');
insert into genres values(2, 'Cops');
insert into genres values(3, 'Dance');
insert into genres values(4, 'Sing');
insert into genres values(5, 'Reality');
insert into genres values(6, 'Mystery');
insert into genres values(7, 'Game Show');
insert into genres values(8, 'Cooking');
insert into genres values(9, 'Drama');
insert into genres values(10, 'Shopping');
insert into genres values(11, 'Sci Fi');
insert into genres values(12, 'Bro');
insert into genres values(13, 'Sports');
insert into genres values(14, 'Talk Show');
insert into genres values(15, 'Late Nite');
insert into genres values(16, 'Cartoons');
insert into genres values(17, 'News');
insert into genres values(18, 'Music');
insert into genres values(19, 'Cars');
insert into genres values(20, 'Horror');
insert into genres values(21, 'Vampires');
insert into genres values(22, 'Suspense');
insert into genres values(23, 'Super Hero');

insert into friends values(1, '/static/img/friends/friend1.png','Neha Narula');
insert into friends values(2, '/static/img/friends/friend2.png','Erin Smith');
insert into friends values(3, '/static/img/friends/friend3.png','Alex Cheng');
insert into friends values(4, '/static/img/friends/friend4.png','Markus Bohn');
insert into friends values(5, '/static/img/friends/friend5.png','Aatman Shah');
insert into friends values(6, '/static/img/friends/friend6.png','Andrew Milne');
insert into friends values(7, '/static/img/friends/friend7.png','Markus Bohn');
insert into friends values(8, '/static/img/friends/friend8.png','Aatman Shah');
insert into friends values(9, '/static/img/friends/friend9.png','Andrew Milne');
insert into friends values(10, '/static/img/friends/friend10.png','Andrew Milne');
insert into friends values(11, '/static/img/friends/friend11.png','Markus Bohn');
insert into friends values(12, '/static/img/friends/friend12.png','Aatman Shah');
insert into friends values(13, '/static/img/friends/friend13.png','Andrew Milne');
insert into friends values(14, '/static/img/friends/friend14.png','Markus Bohn');
insert into friends values(15, '/static/img/friends/friend15.png','Aatman Shah');
insert into friends values(16, '/static/img/friends/friend16.png','Andrew Milne');
insert into friends values(17, '/static/img/friends/friend17.png','Andrew Milne');
insert into friends values(18, '/static/img/friends/friend18.png','Andrew Milne');
insert into friends values(19, '/static/img/friends/friend19.png','Markus Bohn');
insert into friends values(20, '/static/img/friends/friend20.png','Aatman Shah');
insert into friends values(21, '/static/img/friends/friend21.png','Andrew Milne');
insert into friends values(22, '/static/img/friends/friend22.png','Markus Bohn');
insert into friends values(23, '/static/img/friends/friend23.png','Aatman Shah');
insert into friends values(24, '/static/img/friends/friend24.png','Andrew Milne');
insert into friends values(25, '/static/img/friends/friend25.png','Andrew Milne');
insert into friends values(26, '/static/img/friends/friend26.png','Andrew Milne');
insert into friends values(27, '/static/img/friends/friend27.png','Andrew Milne');
insert into friends values(28, '/static/img/friends/friend28.png','Andrew Milne');
insert into friends values(29, '/static/img/friends/friend29.png','Markus Bohn');
insert into friends values(30, '/static/img/friends/friend30.png','Aatman Shah');
insert into friends values(31, '/static/img/friends/friend31.png','Andrew Milne');
insert into friends values(32, '/static/img/friends/friend32.png','Markus Bohn');
insert into friends values(33, '/static/img/friends/friend33.png','Aatman Shah');
insert into friends values(34, '/static/img/friends/friend34.png','Andrew Milne');
insert into friends values(35, '/static/img/friends/friend35.png','Andrew Milne');

insert into watchbox values(0,0);
insert into watchbox values(0,3);
insert into watchbox values(0,6);
insert into watchbox values(1,1);
insert into watchbox values(1,2);