insert into tvshows values(0, 0, '30rock', 'static/img/tv/30rock.jpg',   '', 'Season 5, Episode 4', 'Liz Lemon finds herself in a dilemma.  Cabletown is in trouble, Jack is gone, and Liz must take over.');
insert into tvshows values(1, 1, 'Gossip Girl', 'static/img/tv/gossipgirl.jpg', '', 'Season 5, Episode 4','Chuck and Blair blah blah');
insert into tvshows values(2, 1, 'Revenge', 'static/img/tv/revenge.jpg', '','Season 3, Episode 8','She gets her revenge');
insert into tvshows values(3, 0, 'How I Met Your Mother', 'static/img/tv/himym_S07E01.jpg', 'static/video/himym/S07E01 The Best Man.avi', 'Season 7, Episode 1','The Best Man Ted attends a wedding');
insert into tvshows values(4, 0, 'How I Met Your Mother', 'static/img/tv/himym_S07E02.jpg', 'static/video/himym/S07E02 The Naked Truth.avi', 'Season 7, Episode 2','The Naked Truth');		
insert into tvshows values(5, 0, 'How I Met Your Mother', 'static/img/tv/himym_S07E03.jpg', 'static/video/himym/S07E03 Ducky Tie.avi', 'Season 7, Episode 3','Ducky Tie');
insert into tvshows values(6, 0, 'New Girl', 'static/img/tv/newgirl_S01E01.jpg', 'static/video/newgirl/S01E01 Pilot.avi', 'Season 1, Episode 1','Pilot Jess moves in with the guys');
insert into tvshows values(7, 0, 'New Girl', 'static/img/tv/newgirl_S01E02.jpg', 'static/video/newgirl/S01E02 Kryptonite.avi', 'Season 1, Episode 2','Kryptonite');
insert into tvshows values(8, 0, 'New Girl', 'static/img/tv/newgirl_S01E03.jpg', 'static/video/newgirl/S01E03 Wedding.avi', 'Season 1, Episode 3','Wedding Jess tries to help Nick make his ex jealous, but everything just ends up going wrong');

insert into genres values(0, 'Comedy');
insert into genres values(1, 'Girly');
insert into genres values(2, 'Cops');
insert into genres values(3, 'Dance');
insert into genres values(4, 'Sing');
insert into genres values(5, 'Reality');
insert into genres values(6, 'Mystery');
insert into genres values(7, 'Game Show');
insert into genres values(8, 'Cooking');
insert into genres values(9, 'Drama');
insert into genres values(10, 'Shopping');
insert into genres values(11, 'Sci Fi');
insert into genres values(12, 'Bro');
insert into genres values(13, 'Sports');
insert into genres values(14, 'Talk Show');
insert into genres values(15, 'Late Nite');
insert into genres values(16, 'Cartoons');
insert into genres values(17, 'News');
insert into genres values(18, 'Music');
insert into genres values(19, 'Cars');
insert into genres values(20, 'Horror');
insert into genres values(21, 'Vampires');
insert into genres values(22, 'Suspense');
insert into genres values(23, 'Super Hero');

insert into friends values(1, '/static/img/friends/friend1.jpg','Sam Gruskin');
insert into friends values(2, '/static/img/friends/friend2.jpg','Erin Smith');
insert into friends values(3, '/static/img/friends/friend3.jpg','Alex Cheng');
insert into friends values(4, '/static/img/friends/friend4.jpg','Markus Bohn');
insert into friends values(5, '/static/img/friends/friend5.jpg','Aatman Shah');
insert into friends values(6, '/static/img/friends/friend6.jpg','Andrew Milne');

insert into watchbox values(0,3);
insert into watchbox values(0,6);
insert into watchbox values(0,7);